name: TeleportPlugin
version: 4.0
main: de.CypDasHuhn.TP.main.Main
api-version: '1.20'

commands:
  testcommand:
    description: testCommand
  teleport:
    aliases: t
  teleportUser:
    aliases: [tu, tUser]
  teleportGlobal:
    aliases: [tg, tGlobal]
  teleportSet:
    aliases: [ts, tSet]
  teleportEdit:
    aliases:  [te, tEdit]
  teleportDelete:
    aliases: [td, tDelete]
  teleportTag:
    aliases: [tt, tTag]
  teleportFolder:
    aliases: [tf, tFolder]
  teleportLanguage:
    aliases: [tl, tLanguage]
  teleportPermission:
    aliases: [tpm, tPermission]
